---
title: "Final Project RMD"
author: "Alexis Adams-Clark, Andrew Fridman, & Xi Yang"
date: "11/14/2018"
output: html_document
---

```{r setup, include = FALSE, warning = FALSE, messages = FALSE}
#Load libraries
library(rio)
library(tidyverse)
library(here)
library(knitr)
library(janitor)
library(forcats)
library(Hmisc)
library(gridExtra)
theme_set(theme_minimal())
```

```{r import data, include = FALSE, warning = FALSE, messages = FALSE}
#Import data
list(here())
data <- import(here("Data", "Final_project_simulated_data.csv"))
#View(data)
```

#  Data Tables and Visualizations
```{r data table, warning = FALSE, messages = FALSE}
#Clean names, make lowercase
data <- data %>% 
  clean_names() %>% 
  mutate(ses = as.factor(ses), 
         ed = as.factor(ed),
         en = as.factor(en),
         sq1 = as.numeric(sq1),
         sq2 = as.numeric(sq2),
         sq3 = as.numeric(sq3), 
         sq4 = as.numeric(sq4),
         mdd1 = as.numeric(mdd1),
         mdd2 = as.numeric(mdd2),
         mdd3 = as.numeric(mdd3),
         ql1 = as.numeric(ql1),
         ql2 = as.numeric(ql2),
         ql3 = as.numeric(ql3))

#Create total scores
#sq = sleep quality, mdd = major depression, ql = quality of life
data <- data %>% 
  mutate(sq_total = sq1 + sq2 + sq3 + sq4, 
         mdd_total = mdd1 + mdd2 + mdd3,
         ql_total = ql1 + ql2 + ql3)

#Grouping by ses and creating a summary of Depression (mdd), Sleep Quality (sq), and Quality of Life (ql) total scores
scorebyses <- data %>% 
  group_by(ses) %>% 
  dplyr::summarize(mean_mdd = mean(mdd_total),
            mean_sq = mean(sq_total),
            mean_ql = mean(ql_total))

#Change levels of ses
levels(scorebyses$ses)
scorebyses <- scorebyses %>% 
  mutate(ses = fct_recode(ses, "High" = "HighSES", 
                               "Med" = "MiddleSES",
                               "Low" = "LowSES"))

scorebyses$ses <- factor(scorebyses$ses, levels = c("Low", "Med", "High"))

#Table summary of scores by ses
kable(scorebyses, format = "html", digits = round(2))
```

```{r data visualization 1}
#Bar graph of mdd scores by ses

ggplot(scorebyses, aes(x = ses, y = mean_mdd, fill = ses)) + 
  geom_col(alpha = 0.7) + 
  labs(title = "Depression Scores by SES", 
       y = "MDD Total Score", 
       x = "Socioeconomic Status") + 
  guides(fill=FALSE) #remove legend

```

```{r Data visualization 2}
#Global settings
opts_chunk$set(fig.width = 5, fig.height = 7)

#Select and filter data, looking at relationships between three outcome variables (depression, sleep quality, and quality of life) in low SES individuals
data_p <- data %>%  
                select(id, ses, en, sq_total, mdd_total, ql_total) %>% 
                filter(ses == "LowSES")

#Scatterplot of sleep quality vs. depression
sp1 <- ggplot(data_p, aes(x = sq_total, y = mdd_total)) + 
              geom_point(position = position_jitter(w = 0.1, h = 0), alpha = 0.7) + 
              geom_smooth(method = "lm") +
              labs(title = "Sleep Quality & Depression",
                   x = "Sleep Quality", 
                   y = "Depression")

#Scatterplot of quality of life vs. depression
sp2 <- ggplot(data_p, aes(x = sq_total, y = ql_total)) + 
              geom_point(position = position_jitter(w = 0.1, h = 0), alpha = 0.7) + 
              geom_smooth(method = "lm") +
              labs(title = "Sleep Quality & Quality of Life",
                   x = "Sleep Quality", 
                   y = "Quality of Life")

#Scatterplot of quality of life vs. depression
sp3 <- ggplot(data_p, aes(x = ql_total, y = mdd_total)) + 
              geom_point(position = position_jitter(w = 0.1, h = 0), alpha = 0.7) + 
              geom_smooth(method = "lm") +
              labs(title = "Quality of Life & Depression",
                   x = "Quality of Life", 
                   y = "Depression")

#Facet wrap three plots
sp_grid <- grid.arrange(sp1, sp2, sp3, 
                        ncol = 1,
                        top = "The Association between Study Measures in Low SES Individuals")
```

```{r correlations}
#Correlations between the three outome variables
data_corr <- data %>% 
  select(ends_with("total"))

#Pretty correlation table with Pearson r
corr <- cor(data_corr)
kable(corr)

#Correlation values with p-values
rcorr(as.matrix(data_corr))
```

The mean total depression score for the sample is `r round(mean(data$mdd_total), 2)` . The mean total sleep quality score for the sample is `r round(mean(data$sq_total), 2)`. The mean quality of life score for the sample is `r round(mean(data$ql_total), 2)`. 

# Demonstrate tidying messy data
```{r gather, separate, select, filter & spread}
#Gather, separate, and spread demo
data_t <- data %>%  
                select(id, ses, 5:14) %>% 
                gather(items, Value, -1:-2) %>% 
                separate(items, c("Measure", "Item"), sep = "(?=[:digit:])", convert = TRUE) %>% 
                group_by(ses, Measure, Item) %>% 
                summarise(Value_mean = mean(Value)) %>% 
                spread(key = ses, value = Value_mean) %>% 
                mutate(DiffSES = LowSES - HighSES) %>% 
                select(Measure, Item, DiffSES) %>% 
                spread(key = Measure, value = Item) %>% 
                arrange(mdd, ql, sq)
View(data_t)
kable(data_t)
```

```{r Plot tidy data}
#Subset data for plot
data_tp <- data_t %>%  
                filter(Measure == "mdd")

#Scatterplot of tidy data
ggplot(data_tp, aes(x = Item, y = DiffSES)) + 
  geom_col(alpha = 0.7) + 
  labs(title = "Low-to-High SES Difference in MDD scores",
       x = "Item", 
       y = "Difference")
```
